LOW_PRIORITY = 0
HIGH_PRIORITY = 1

FCFS_QUEUING = 0
PRIORITY_QUEUING = 19
MODIFIED_PRIORITY_QUEUING = 2
EDF_QUEUING = 3

TIME_ADVANCE = 1e-6  # in time unit
PACKETS_TARGET = 1000000  # number of packets to simulate)\
MAX_RESOURCE_BLOCKS = 100
DISCRETE_RESOURCE_ALLOCATIONS = [6, 15, 25, 50, 75, 100]

PRIORITIES_ARRIVAL_RATE_PROPORTION = {LOW_PRIORITY: 0.8, HIGH_PRIORITY: 0.2}
PRIORITIES_DEADLINE_RANGES = {HIGH_PRIORITY: (0.001, 0.150),
                              LOW_PRIORITY: (0.150, 1)}  # in time units
