LOW_PRIORITY = 0
HIGH_PRIORITY = 1

FCFS_QUEUING = 0
PRIORITY_QUEUING = 1
MODIFIED_PRIORITY_QUEUING = 2
EDF_QUEUING = 3

TIME_ADVANCE = 1e-6  # in time unit
PACKETS_TARGET = 10  # number of packets to simulate)\
MAX_RESOURCE_BLOCKS = 100
DISCRETE_RESOURCE_ALLOCATIONS = [6, 15, 25, 50, 75, 100]

PRIORITIES_ARRIVAL_RATE_PROPORTION = {LOW_PRIORITY: 0.7, HIGH_PRIORITY: 0.3}
PRIORITIES_DEADLINE_RANGES = {HIGH_PRIORITY: (1e-3, 300e-3),
                              LOW_PRIORITY: (1, 100)}  # in time units
